apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codevantaos-system
commonLabels:
  platform: codevantaos
  managed-by: gitops
resources:
  - service-account.yaml
  - role-binding.yaml
