#!/usr/bin/env python3
"""Autonomous Bot — Phase 2: Create GitHub Issues (deduplicated)."""
import json, os, urllib.request
from datetime import datetime, timezone

token = os.environ.get("GITHUB_TOKEN", "")
repo = os.environ.get("GITHUB_REPOSITORY", "")
dry_run = os.environ.get("DRY_RUN", "false") == "true"
problems_raw = os.environ.get("PROBLEMS_JSON", "[]")
problems = json.loads(problems_raw.replace('%0A', '\n').replace('%0D', '\r').replace('%25', '%'))

def gh_api(path, method="GET", data=None):
    url = f"https://api.github.com/repos/{repo}{path}"
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json", "Content-Type": "application/json"}
    req = urllib.request.Request(url, headers=headers, method=method, data=json.dumps(data).encode() if data else None)
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read())
    except Exception as e:
        print(f"API error {path}: {e}")
        return {}

existing = gh_api("/issues?state=open&per_page=100&labels=autonomous-bot")
existing_titles = {i["title"] for i in existing} if isinstance(existing, list) else set()

issue_map = {}
issues_created = 0
severity_labels = {
    "critical": ["autonomous-bot", "critical", "security"],
    "high": ["autonomous-bot", "high-priority", "bug"],
    "medium": ["autonomous-bot", "medium-priority"],
    "low": ["autonomous-bot", "low-priority", "stale"],
}

for p in problems:
    title = f"[bot] {p['title']}"
    if title in existing_titles:
        print(f"Skipping (already exists): {title}")
        for i in (existing if isinstance(existing, list) else []):
            if i["title"] == title:
                issue_map[p["id"]] = i["number"]
                break
        continue

    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    body = (
        "## Autonomous Bot Detection Report\n\n"
        f"Problem ID: `{p['id']}`\n"
        f"Type: `{p['type']}`\n"
        f"Severity: `{p['severity'].upper()}`\n"
        f"Detected at: {now}\n"
        f"Auto-fixable: {'Yes' if p['auto_fixable'] else 'No - Manual review required'}\n"
        f"Fix strategy: `{p.get('fix_strategy', 'manual')}`\n\n"
        "---\n\n"
        "### Description\n\n"
        f"{p['description']}\n\n"
        "---\n\n"
        "### Next Steps\n\n"
        + ('This issue will be automatically fixed by the bot. A fix branch and PR will be created shortly.'
           if p['auto_fixable'] else 'This issue requires manual review. Please investigate and resolve.')
        + f"\n\n---\n\n> Auto-generated by Autonomous Bot workflow.\n> Do not close manually — the bot will close this issue when the fix is merged."
    )
    labels = severity_labels.get(p["severity"], ["autonomous-bot"])

    if dry_run:
        print(f"[DRY RUN] Would create issue: {title}")
        issue_map[p["id"]] = 0
    else:
        result = gh_api("/issues", method="POST", data={"title": title, "body": body, "labels": labels})
        if result.get("number"):
            issue_map[p["id"]] = result["number"]
            issues_created += 1
            print(f"Created issue #{result['number']}: {title}")
        else:
            print(f"Failed to create issue: {title}")

print(f"\nTotal issues created: {issues_created}")
with open(os.environ.get("GITHUB_OUTPUT", "/dev/null"), "a") as f:
    f.write(f"issues_created={issues_created}\n")
    escaped = json.dumps(issue_map).replace('%', '%25').replace('\n', '%0A')
    f.write(f"issue_map_json={escaped}\n")
