#!/usr/bin/env python3
"""Autonomous Bot — Phase 4: Open Pull Request."""
import json, os, urllib.request
from datetime import datetime, timezone

token = os.environ.get("GITHUB_TOKEN", "")
repo = os.environ.get("GITHUB_REPOSITORY", "")
branch = os.environ.get("BRANCH_NAME", "")
fixes = os.environ.get("FIXES_SUMMARY", "")
problem_count = os.environ.get("PROBLEM_COUNT", "0")
dry_run = os.environ.get("DRY_RUN", "false") == "true"
issue_map_raw = os.environ.get("ISSUE_MAP_JSON", "{}")
issue_map = json.loads(issue_map_raw.replace('%0A', '\n').replace('%25', '%'))

if not branch:
    print("No branch to create PR for.")
    with open(os.environ.get("GITHUB_OUTPUT", "/dev/null"), "a") as f:
        f.write("pr_number=0\npr_url=\n")
    exit(0)

def gh_api(path, method="GET", data=None):
    url = f"https://api.github.com/repos/{repo}{path}"
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json", "Content-Type": "application/json"}
    req = urllib.request.Request(url, headers=headers, method=method, data=json.dumps(data).encode() if data else None)
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        print(f"HTTP {e.code}: {e.read().decode()[:200]}")
        return {}
    except Exception as e:
        print(f"API error {path}: {e}")
        return {}

closes_lines = "\n".join([f"Closes #{num}" for num in issue_map.values() if num and num > 0])
now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
title = f"fix(bot): autonomous fixes — {now}"
body = (
    "## Autonomous Bot Fix PR\n\n"
    f"This PR was automatically created by the Autonomous Bot.\n\n"
    "### What was detected and fixed\n\n"
    f"{fixes}\n\n"
    f"### Problems addressed ({problem_count} total)\n\n"
    f"{closes_lines if closes_lines else '_No linked issues_'}\n\n"
    "### Verification checklist (auto-validated)\n\n"
    "- CI validator: 0 errors\n"
    "- All GitHub Actions pinned to full SHA\n"
    "- OPA governance policy: all .qyaml files compliant\n"
    "- YAML syntax valid for all workflow files\n\n"
    "### Merge strategy\n\n"
    "This PR is eligible for automatic merge once all CI checks pass.\n\n"
    f"> Auto-generated by Autonomous Bot | Run: {os.environ.get('GITHUB_RUN_ID', '')}\n"
    "> Squash merge strategy per eco-base best practices."
)

if dry_run:
    print(f"[DRY RUN] Would create PR: {title}")
    with open(os.environ.get("GITHUB_OUTPUT", "/dev/null"), "a") as f:
        f.write("pr_number=0\npr_url=\n")
    exit(0)

# Check if PR already exists
existing_prs = gh_api(f"/pulls?head={repo.split('/')[0]}:{branch}&state=open")
if isinstance(existing_prs, list) and existing_prs:
    pr = existing_prs[0]
    print(f"PR already exists: #{pr['number']} — {pr['html_url']}")
    with open(os.environ.get("GITHUB_OUTPUT", "/dev/null"), "a") as f:
        f.write(f"pr_number={pr['number']}\npr_url={pr['html_url']}\n")
    exit(0)

pr = gh_api("/pulls", method="POST", data={"title": title, "body": body, "head": branch, "base": "main", "draft": False})
if pr.get("number"):
    pr_number = pr["number"]
    pr_url = pr["html_url"]
    print(f"Created PR #{pr_number}: {pr_url}")
    gh_api(f"/issues/{pr_number}/labels", method="POST", data={"labels": ["autonomous-bot", "auto-merge", "bot"]})
    # Enable auto-merge via GraphQL
    pr_node_id = pr.get("node_id", "")
    if pr_node_id:
        mutation = {"query": f'mutation {{ enablePullRequestAutoMerge(input: {{pullRequestId: "{pr_node_id}", mergeMethod: SQUASH}}) {{ pullRequest {{ autoMergeRequest {{ enabledAt }} }} }} }}'}
        gql_req = urllib.request.Request("https://api.github.com/graphql", data=json.dumps(mutation).encode(), method="POST",
            headers={"Authorization": f"token {token}", "Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(gql_req) as r:
                result = json.loads(r.read())
                if result.get("data"):
                    print(f"Auto-merge enabled for PR #{pr_number}")
        except Exception as e:
            print(f"Auto-merge GraphQL: {e}")
    with open(os.environ.get("GITHUB_OUTPUT", "/dev/null"), "a") as f:
        f.write(f"pr_number={pr_number}\npr_url={pr_url}\n")
else:
    print(f"Failed to create PR: {pr}")
    with open(os.environ.get("GITHUB_OUTPUT", "/dev/null"), "a") as f:
        f.write("pr_number=0\npr_url=\n")
